### PR TITLE
Bugfix/label #3201

### PR DESCRIPTION
**Pull request by cayop**
fix bugs detected in [#3144](https://tree.taiga.io/project/usody/task/3144) --> [US #3201](https://tree.taiga.io/project/usody/t/3201)

### CODE REVIEW

**Comment by slamora** [comment]
Layout is broken on laptop size: width = 1440px
image

**Comment by slamora** [comment]
This PR maybe superseed by #236

**Comment by RubenPX** [comment]
> This PR maybe superseed by #236

It's recomended to use simpleDatatables variable --> [device_list.html#Ln414](https://github.com/eReuse/devicehub-teal/blob/testing/ereuse_devicehub/templates/inventory/device_list.html#L414)

One hint: https://github.com/eReuse/devicehub-teal/pull/241/commits/770ab8ea8d598845ca94a946a83767cb2b5532bc#diff-2da64aefb2ecccbfe37a525c897bbdc2a65b74202784f2a51ceaa136445a7056R355

> Think: In this pull request i will use python device model into javascript to make more easy manage some info

**Comment by RubenPX** [comment]
Fixed in https://github.com/eReuse/devicehub-teal/pull/241

**Pull request closed without merging**
