### PR TITLE
feature/22-device lot visibility

### PR DESCRIPTION
**Pull request by forste**

### CODE REVIEW

**Comment by forste** [comment]
Implements https://github.com/eReuse/devicehub-teal/issues/22

**Comment by fedjo** [comment]
If the functionality is tested I believe we can merge it.

**Comment by forste** [comment]
I can't test it _before_ deploying it to testing server, because I can not run this locally. However, AFAIK this has been deployed to the testing server already

**Comment by forste** [comment]
@JNadeu can you test this PR locally please before @fedjo merges it into `testing`?

**Comment by JNadeu** [comment]
> I can't test it _before_ deploying it to testing server, because I can not run this locally. However, AFAIK this has been deployed to the testing server already

@forste  Currently in the test server there is already the branch of this feature, and it seems that everything works correctly. 

@fedjo As for me, we can close this PR! What do you think?

**Comment by fedjo** [comment]
> > I can't test it _before_ deploying it to testing server, because I can not run this locally. However, AFAIK this has been deployed to the testing server already
> 
> @forste Currently in the test server there is already the branch of this feature, and it seems that everything works correctly.
> 
> @fedjo As for me, we can close this PR! What do you think?

Sure @JNadeu . Close and merge?

**Comment by JNadeu** [comment]
@cayop Can you help me fixing 4 export tests on test_documents.py that fails with same error:  _AttributeError: '_AppCtxGlobals' object has no attribute 'user'_ ?

I think then we can approve it! :-)

**Comment by cayop** [comment]
* test_export_multiple_different_devices
Please check if line 225 makes sense:
  "fixture_csv[:3] == export_csv" instead of "fixture_csv == export_csv"

* test_export_computer_monitor
problems with visibility_filter:
  query.filter((Computer.id == Device.id), (Computer.owner_id == g.user.id)) == []

I don't know why.

**Comment by JNadeu** [comment]
At the moment we only support the export of computer type devices or derivatives. 
Therefore _test_export_multiple_different_devices_ and _test_export_computer_monitor_ are out for the moment.

**Pull request merged**
