### PR TITLE
alembic migrations

### PR DESCRIPTION
**Pull request by slamora**
Follows #29 that has been created with base and source branch swapped.

> This pull request aims to set up `alembic` migration tool for the app.
> 
> For more info on how to set up migrations read README
> 
> Please provide any feedback

### CODE REVIEW

**Comment by slamora** [comment]
From [README.rst](https://github.com/eReuse/devicehub-teal/tree/feature/alembic-migrations#migrations)
> Whenever you want to create a new schema just create a new revision with:
> $ alembic revision -m "My new base revision"
> $ export dhi=dbtest2; dh inv add --name dbtest2

@fedjo Seems that each dh inventory requires a specific alembic migrations. As a migration is a python script, I think that it doesn't have sense having inventory and code coupled.

I wonder if there is a way to use the same alembic migration that is run against all the schemas (inventories) that exists on the devicehub instance.

Maybe I'm not understanding properly devicehub & alembic migrations?

**Comment by fedjo** [comment]
> From [README.rst](https://github.com/eReuse/devicehub-teal/tree/feature/alembic-migrations#migrations)
> 
> > Whenever you want to create a new schema just create a new revision with:
> > $ alembic revision -m "My new base revision"
> > $ export dhi=dbtest2; dh inv add --name dbtest2
> 
> @fedjo Seems that each dh inventory requires a specific alembic migrations. As a migration is a python script, I think that it doesn't have sense having inventory and code coupled.
> 
> I wonder if there is a way to use the same alembic migration that is run against all the schemas (inventories) that exists on the devicehub instance.
> 

@slamora can you provide an example to make more clear what you mean?

**Comment by slamora** [comment]
Sorry! I was wrong! I thinked that run this command is required to initalize the database but it's needed while your are developing and you made some changes on the models.
```bash
$ alembic revision -m "My new base revision"
```

Please, forget my previous comment.

Related to the pull request, I think that we should add `alembic` to `requirements.txt`. Could do it myself?

**Comment by fedjo** [comment]
Sure I will update

**Comment by slamora** [comment]
I've tested the PR and I think that is ready for review (and merge). @JNadeu @emmdim As you have a more deeply knowledge about devicehub-teal code, could you do a final review before merging? Thanks.

**Pull request merged**
