### PR TITLE
WIP: filter in out trades from lots selector

### PR DESCRIPTION
**Pull request by RubenPX**
- [X] Filter by trade options c8dc1b11e225103848b3a786c17843259e0178b8
- [X] Optimize using python insteado of client javascript a945fc085f05f8ed1c1c9fe135dbf70612bf6747
- [X] Document API 2ffa606bc356bc966bf12bd9f2b8f648d18170f1

### CODE REVIEW

**Comment by slamora** [comment]
@RubenPX as we've talked I think that we can optimize code filtering lots on server side. I leave here the diff of a prototype that you could complete:
```diff
diff --git a/ereuse_devicehub/resources/lot/views.py b/ereuse_devicehub/resources/lot/views.py
index dce6af6..61625af 100644
--- a/ereuse_devicehub/resources/lot/views.py
+++ b/ereuse_devicehub/resources/lot/views.py
@@ -88,6 +88,8 @@ class LotView(View):
         else:
             query = Lot.query
             query = self.visibility_filter(query)
+            query = self.type_filter(query, args)
+
             if args['search']:
                 query = query.filter(Lot.name.ilike(args['search'] + '%'))
             lots = query.paginate(per_page=6 if args['search'] else query.count())
@@ -104,6 +106,16 @@ class LotView(View):
                         Lot.owner_id == g.user.id))
         return query
 
+    def type_filter(self, query, args):
+        lot_type = args.get('type')
+
+        # TODO(@slamora) needed implement incoming & outgoing filters
+        if lot_type is None or lot_type not in ['temporary']:
+            return query
+
+        # temporary
+        return query.filter(Lot.trade == None)
+
     def query(self, args):
         query = Lot.query.distinct()
         return query

```

- [ ] Finish started implementation of filter: accepted values `incoming`, `outgoing` & `temporary` through parameter `type`
- [ ] Write tests to check new filter by type on `/lots/` endpoint.

**Comment by RubenPX** [comment]
@slamora 

I tried something, add var type to query, simply creating a new variable... Maybe this can help?

https://github.com/eReuse/devicehub-teal/pull/233#issuecomment-1108814888

```diff
vscode ➜ /workspace (feature/confirm-trade-changes ✗) $ diff -u "/workspace/ereuse_devicehub/resources/lot/views.py" "/workspace/ereuse_devicehub/resources/lot/views copy.py"
--- /workspace/ereuse_devicehub/resources/lot/views.py  2022-04-27 09:19:03.628997700 +0000
+++ "/workspace/ereuse_devicehub/resources/lot/views copy.py"   2022-04-27 09:18:57.464817500 +0000
@@ -29,6 +29,7 @@
         """
         format = EnumField(LotFormat, missing=None)
         search = f.Str(missing=None)
+        type = f.Str(missing=None)
 
     def post(self):
         l = request.get_json()
@@ -88,6 +89,8 @@
         else:
             query = Lot.query
             query = self.visibility_filter(query)
+            query = self.type_filter(query, args)
             if args['search']:
                 query = query.filter(Lot.name.ilike(args['search'] + '%'))
             lots = query.paginate(per_page=6 if args['search'] else query.count())
@@ -104,6 +107,15 @@
                         Lot.owner_id == g.user.id))
         return query
 
+    def type_filter(self, query, args):
+        lot_type = args.get('type')
+
+        # temporary
+        if lot_type == "temporary":
+            return query.filter(Lot.trade == None)
+
+        return query
+
     def query(self, args):
         query = Lot.query.distinct()
         return query
```

**Comment by RubenPX** [comment]
One question, it's possible to call or get properties from an user Object... Basically querys is a copy paste from `/lot/models.py` 
https://github.com/eReuse/devicehub-teal/pull/233/commits/c8dc1b11e225103848b3a786c17843259e0178b8

**Review by slamora — APPROVED** [review]

**Comment by slamora** [comment]
> One question, it's possible to call or get properties from an user Object using SQLAlchemy? Basically querys is a copy paste from `/lot/models.py` https://github.com/eReuse/devicehub-teal/blob/testing/ereuse_devicehub/resources/lot/models.py#L104
> 
> [c8dc1b1](https://github.com/eReuse/devicehub-teal/commit/c8dc1b11e225103848b3a786c17843259e0178b8)

Sorry but you cannot perform SQL queries against python code (`is_temporary` is a property).

**Pull request merged**
